apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ .Release.Name }}-pvc
  namespace: {{ .Release.Namespace }}
spec:
  resources:
    requests:
      storage: {{ .Values.disk_size }}
  volumeMode: Filesystem
  storageClassName: {{ .Values.storage_class }}
  accessModes:
    - ReadWriteOnce