apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-redis-depl
  namespace: {{ .Release.Namespace }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: {{ .Release.Name }}-redis
  template:
    metadata:
      labels:
        app: {{ .Release.Name }}-redis
    spec:
      containers:
      - name: redis
        image: redis:6.2.4-alpine3.14
        resources:
          limits:
            memory: "16Mi"
            cpu: "10m"
          requests:
            memory: "8Mi"
            cpu: "5m"
        ports:
        - containerPort: 6379
---
apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-redis-srv
spec:
  selector:
    app: {{ .Release.Name }}-redis
  ports:
  - port: 6379
    targetPort: 6379