apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-secret
  namespace: {{ .Release.Namespace }}
type: Opaque
data:
  JUDGE_SERVER_TOKEN: {{ .Values.judge_server_token | b64enc | quote }}
  POSTGRES_USER: {{ .Values.postgres.username | b64enc | quote }}
  POSTGRES_PASSWORD: {{ .Values.postgres.password | b64enc | quote }}